package clihelp

import (
	"fmt"
	"os"
	"strings"
)

// The unattended path.
//
// This is the only code in the library that writes to a user's home directory
// without being asked, so it lives apart from the explicit installers in
// install.go and is held to a much narrower rule: it may refresh a file that
// already exists and carries clihelp's marker, and it may do nothing else.
// See App.AutoRefreshIntegration.

// maybeRefreshIntegration brings an already-installed integration up to date,
// silently, if the author asked for it.
func (a *App) maybeRefreshIntegration(args []string) {
	if a == nil || !a.AutoRefreshIntegration {
		return
	}
	// Never run during an internal protocol call — a setup call must not have an
	// install as a side effect — or in CI/non-interactive test runs.
	if len(args) > 0 && strings.HasPrefix(args[0], "__") {
		return
	}
	if os.Getenv("CI") != "" || os.Getenv("GITHUB_ACTIONS") != "" || os.Getenv("TERM") == "dumb" || os.Getenv("NO_AUTO_COMPLETION") != "" || os.Getenv("CLIHELP_NO_AUTO_COMPLETION") != "" {
		return
	}
	a.refreshManPage()

	sh, err := resolveShell("")
	if err != nil {
		return // no script exists for this shell; writing a bash one would be a lie
	}
	// A shell integration the user installed is kept current, and never created
	// here: a key binding appearing in someone's shell because they happened to
	// run an unrelated command would be an overreach, and editing a startup file
	// unasked doubly so.
	if path, err := integrationPath(a, sh); err == nil {
		if _, statErr := os.Stat(uninstalledMarker(path)); statErr == nil {
			return // the user removed it on purpose; putting anything back is not ours to do
		}
		if _, statErr := os.Stat(path); statErr == nil {
			if !integrationIsCurrent(path) {
				// Refresh only: an ordinary program run rewrites the generated
				// file and never touches a startup file.
				autoDebug(a, refreshShellIntegration(a, sh, integrationHasKeys(path)))
			}
			return
		}
	}
	// A completion script at the older location — installed before this library
	// grew its one-file integration, or by a packager — is kept current, and
	// that is all. This path runs on every ordinary program run, unasked, and
	// bringing a file into existence in someone's home directory is not a
	// decision it gets to make: AutoRefreshIntegration is the *author's* choice,
	// while the file lands in the *user's* home. It used to create one here, so
	// running a program for the first time installed something nobody had asked
	// for. Creating is what "completion install" is for.
	//
	// Overwriting is also only safe when this library wrote the file:
	// completionIsCurrent answers "no marker" for a *foreign* script exactly as
	// it does for a stale one, so without the marker check a hand-written
	// completion was read as out of date and replaced by an ordinary command.
	path, err := completionScriptPath(a, sh)
	if err != nil {
		return
	}
	if _, statErr := os.Stat(path); statErr != nil {
		return
	}
	if isGeneratedCompletionScript(path) && !completionIsCurrent(a, sh) {
		_, installErr := installCompletion(a, sh)
		autoDebug(a, installErr)
	}
}

// autoDebug surfaces an error the auto path would otherwise swallow, when
// CLIHELP_DEBUG is set.
//
// Discarding these is the right default — the user ran a command of their own,
// not an installer — but without an escape hatch a half-finished install is
// undiagnosable: "completion stopped working after the upgrade", no error, no
// log, and no way to ask.
func autoDebug(a *App, err error) {
	if err == nil || os.Getenv("CLIHELP_DEBUG") == "" {
		return
	}
	fmt.Fprintf(a.stderr(), "clihelp: %v\n", err)
}

// isGeneratedCompletionScript reports whether this library wrote the script at
// path. The delete path in install.go has always asked this question before
// removing a file; the write path did not.
func isGeneratedCompletionScript(path string) bool {
	return fileHasMarker(path, "clihelp-completion-version:", markerWindow)
}

// completionIsCurrent reports whether the installed script was generated by this
// version of the templates. isCompletionInstalled keeps its documented meaning
// ("a script exists"); staleness is checked only where a rewrite is safe.
func completionIsCurrent(app *App, shell string) bool {
	path, err := completionScriptPath(app, shell)
	if err != nil {
		return true // nothing we could install anyway
	}
	return fileHasMarker(path, fmt.Sprintf("clihelp-completion-version: %d", completionScriptVersion), markerWindow)
}
