package clihelp

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Shell integration is installed as one file per shell under the application's
// own configuration directory, plus one permanent line in the shell's startup
// file that sources it.
//
// The file holds both halves — the completion registration and the Alt-H key
// binding — because a key binding has to exist before the key is pressed, while
// every shell loads a completion script lazily, on the first <Tab> for that
// command. Once a startup file has to source something anyway, there is no
// reason left for two artifacts, and putting them in one directory owned by the
// application means one uninstall and no zsh $fpath juggling.
//
// The startup line never changes: it names a fixed path, and the program keeps
// the file at that path current through the version marker in its header. So
// nothing here runs the program at shell startup.
const (
	integrationDirName  = "shell"
	integrationMarkerFn = "clihelp-integration-version"
)

// integrationVersion identifies what the generated file contains. It is derived
// from the two template versions rather than maintained separately, so that
// bumping either one invalidates every installed file.
func integrationVersion() string {
	return fmt.Sprintf("%d.%d", completionScriptVersion, keyDispatcherVersion)
}

// IntegrationPath returns the file the shell startup line sources: one file per
// shell under the application's configuration directory.
func IntegrationPath(app *App, shell string) (string, error) {
	if app == nil {
		return "", errors.New("integration path: app is nil")
	}
	if shell == "" {
		shell = detectShell()
	}
	shell = strings.ToLower(strings.TrimSpace(shell))
	if !isSupportedShell(shell) {
		return "", fmt.Errorf("unsupported shell %q (supported: %s)", shell, strings.Join(SupportedShells, ", "))
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to locate user home directory: %w", err)
	}
	configHome := os.Getenv("XDG_CONFIG_HOME")
	if configHome == "" {
		configHome = filepath.Join(home, ".config")
	}
	return filepath.Join(configHome, appName(app), integrationDirName, shell), nil
}

// GenShellIntegration writes the whole of one shell's integration: a header
// carrying the version marker, the completion script, and — unless keys is
// false — the Alt-H key bindings.
func GenShellIntegration(app *App, shell string, keys bool, w io.Writer) error {
	if app == nil {
		return errors.New("shell integration: app is nil")
	}
	shell = strings.ToLower(strings.TrimSpace(shell))

	var body bytes.Buffer
	var err error
	switch shell {
	case "bash":
		err = GenBashCompletion(app, &body)
	case "zsh":
		err = GenZshCompletion(app, &body)
	case "fish":
		err = GenFishCompletion(app, &body)
	default:
		return fmt.Errorf("unsupported shell %q (supported: %s)", shell, strings.Join(SupportedShells, ", "))
	}
	if err != nil {
		return err
	}
	if keys {
		body.WriteString("\n")
		if err := GenKeyBindings(app, shell, &body); err != nil {
			return err
		}
	}

	header := fmt.Sprintf(`# %[1]s shell integration for %[2]s — tab completion%[4]s.
# %[3]s: %[5]s keys=%[6]s
#
# Generated by "%[1]s completion install", and rewritten by it whenever %[1]s is
# upgraded. Do not edit: your changes would be overwritten. To stop using it,
# run "%[1]s completion uninstall".

`, appName(app), shell, integrationMarkerFn, keysSuffix(keys), integrationVersion(), yesNo(keys))

	if _, err := io.WriteString(w, header); err != nil {
		return err
	}
	_, err = w.Write(body.Bytes())
	return err
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func keysSuffix(keys bool) string {
	if keys {
		return ", and Alt-H to expand and explain the command line"
	}
	return ""
}

// integrationIsCurrent reports whether the installed file was generated by this
// version of the templates.
func integrationIsCurrent(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	head := make([]byte, 512)
	n, _ := f.Read(head)
	return strings.Contains(string(head[:n]), integrationMarkerFn+": "+integrationVersion())
}

// InstallResult reports everything an install or uninstall touched, so the
// command can tell the user exactly what changed in their home directory.
type InstallResult struct {
	Shell       string   // the shell that was set up
	Integration string   // the generated file, "" when it was removed
	Startup     string   // the startup file that sources it
	StartupEdit bool     // whether that startup file was changed
	Removed     []string // files removed: a superseded install, or an uninstall
}

func blockMarkers(app *App) (string, string) {
	name := appName(app)
	return fmt.Sprintf("# >>> %s shell integration (clihelp) >>>", name),
		fmt.Sprintf("# <<< %s shell integration (clihelp) <<<", name)
}

// startupFile names the file that has to source the integration, and reports
// whether clihelp owns that file outright. fish has a real drop-in directory, so
// there the answer is a file of our own and no shared config is touched at all.
func startupFile(app *App, shell string) (path string, owned bool, err error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", false, fmt.Errorf("failed to locate user home directory: %w", err)
	}
	switch shell {
	case "bash":
		return filepath.Join(home, ".bashrc"), false, nil
	case "zsh":
		dir := os.Getenv("ZDOTDIR")
		if dir == "" {
			dir = home
		}
		return filepath.Join(dir, ".zshrc"), false, nil
	case "fish":
		configHome := os.Getenv("XDG_CONFIG_HOME")
		if configHome == "" {
			configHome = filepath.Join(home, ".config")
		}
		return filepath.Join(configHome, "fish", "conf.d", appName(app)+".fish"), true, nil
	}
	return "", false, fmt.Errorf("unsupported shell %q", shell)
}

// bootstrapBlock is the text placed in the startup file. It names a fixed path
// and never changes again: everything that varies lives in the file it sources,
// which the program rewrites on its own.
func bootstrapBlock(app *App, shell, target string) string {
	begin, end := blockMarkers(app)
	name := appName(app)
	note := ""
	if shell == "zsh" {
		note = "# Keep this after compinit: the completion registers itself with compdef.\n"
	}
	source := fmt.Sprintf("[ -r %[1]q ] && . %[1]q\n", target)
	if shell == "fish" {
		source = fmt.Sprintf("test -r %[1]q; and source %[1]q\n", target)
		note = ""
	}
	return fmt.Sprintf(`%s
# Tab completion and the Alt-H key binding for %s. The file sourced below is
# generated, and kept up to date by "%s completion install"; this block is
# permanent. Run "%s completion uninstall" to remove both.
%s%s%s
`, begin, name, name, name, note, source, end)
}

// upsertBlock replaces the marked block in contents, or appends it when there is
// none, and reports whether anything changed.
func upsertBlock(contents, block, begin, end string) (string, bool) {
	if i := strings.Index(contents, begin); i >= 0 {
		rest := contents[i:]
		if j := strings.Index(rest, end); j >= 0 {
			tail := rest[j+len(end):]
			updated := contents[:i] + strings.TrimSuffix(block, "\n") + tail
			return updated, updated != contents
		}
	}
	prefix := contents
	if prefix != "" && !strings.HasSuffix(prefix, "\n") {
		prefix += "\n"
	}
	if prefix != "" {
		prefix += "\n"
	}
	return prefix + block, true
}

// removeBlock takes the marked block out of contents, leaving everything else
// exactly as it was.
func removeBlock(contents, begin, end string) (string, bool) {
	i := strings.Index(contents, begin)
	if i < 0 {
		return contents, false
	}
	rest := contents[i:]
	j := strings.Index(rest, end)
	if j < 0 {
		return contents, false
	}
	tail := strings.TrimPrefix(rest[j+len(end):], "\n")
	head := strings.TrimSuffix(contents[:i], "\n")
	if head != "" && tail != "" {
		head += "\n"
	}
	return head + tail, true
}

// InstallShellIntegration writes the integration file for shell and makes the
// shell source it, and reports everything it touched. With keys false it writes
// only the completion half and still sets up the sourcing.
//
// It is idempotent: re-running it rewrites the generated file and leaves the
// startup file alone unless the block is missing or out of date.
func InstallShellIntegration(app *App, shell string, keys bool) (InstallResult, error) {
	target, err := IntegrationPath(app, shell)
	if err != nil {
		return InstallResult{}, err
	}
	if shell == "" {
		shell = detectShell()
	}
	shell = strings.ToLower(strings.TrimSpace(shell))
	res := InstallResult{Shell: shell, Integration: target}

	var body bytes.Buffer
	if err := GenShellIntegration(app, shell, keys, &body); err != nil {
		return res, err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return res, fmt.Errorf("failed to create directory %q: %w", filepath.Dir(target), err)
	}
	if err := writeFileAtomically(target, body.Bytes(), 0o644); err != nil {
		return res, fmt.Errorf("failed to write %q: %w", target, err)
	}

	res.Startup, res.StartupEdit, err = installBootstrap(app, shell, target)
	if err != nil {
		return res, err
	}
	res.Removed = removeSupersededScript(app, shell)
	return res, nil
}

// installBootstrap puts the sourcing block in the shell's startup file, or
// writes the whole drop-in file for a shell that has a directory for them.
func installBootstrap(app *App, shell, target string) (string, bool, error) {
	path, owned, err := startupFile(app, shell)
	if err != nil {
		return "", false, err
	}
	block := bootstrapBlock(app, shell, target)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return path, false, fmt.Errorf("failed to create directory %q: %w", filepath.Dir(path), err)
	}

	existing, mode, err := readFileWithMode(path)
	if err != nil {
		return path, false, err
	}
	updated := block
	changed := existing != block
	if !owned {
		begin, end := blockMarkers(app)
		updated, changed = upsertBlock(existing, block, begin, end)
	}
	if !changed {
		return path, false, nil
	}
	if err := writeFileAtomically(path, []byte(updated), mode); err != nil {
		return path, false, fmt.Errorf("failed to update %q: %w", path, err)
	}
	return path, true, nil
}

// UninstallShellIntegration removes what InstallShellIntegration wrote: the
// generated file, and the block in the startup file. Nothing else in that file
// is touched.
func UninstallShellIntegration(app *App, shell string) (InstallResult, error) {
	target, err := IntegrationPath(app, shell)
	if err != nil {
		return InstallResult{}, err
	}
	if shell == "" {
		shell = detectShell()
	}
	shell = strings.ToLower(strings.TrimSpace(shell))
	res := InstallResult{Shell: shell}

	if err := os.Remove(target); err == nil {
		res.Removed = append(res.Removed, target)
		_ = os.Remove(filepath.Dir(target)) // only if it is now empty
	} else if !errors.Is(err, os.ErrNotExist) {
		return res, err
	}

	path, owned, err := startupFile(app, shell)
	if err != nil {
		return res, err
	}
	res.Startup = path
	if owned {
		if err := os.Remove(path); err == nil {
			res.Removed = append(res.Removed, path)
			res.StartupEdit = true
		} else if !errors.Is(err, os.ErrNotExist) {
			return res, err
		}
		return res, nil
	}

	existing, mode, err := readFileWithMode(path)
	if err != nil || existing == "" {
		return res, err
	}
	begin, end := blockMarkers(app)
	updated, changed := removeBlock(existing, begin, end)
	if !changed {
		return res, nil
	}
	if err := writeFileAtomically(path, []byte(updated), mode); err != nil {
		return res, fmt.Errorf("failed to update %q: %w", path, err)
	}
	res.StartupEdit = true
	return res, nil
}

// removeSupersededScript deletes a completion script this library installed in
// the shell's own directory before the integration file existed, so that a shell
// does not end up loading two copies. A file without clihelp's marker was
// written by someone else and is left alone.
func removeSupersededScript(app *App, shell string) []string {
	path, err := CompletionPath(app, shell)
	if err != nil {
		return nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	head := data
	if len(head) > 256 {
		head = head[:256]
	}
	if !strings.Contains(string(head), "clihelp-completion-version:") {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return nil
	}
	return []string{path}
}

func readFileWithMode(path string) (string, os.FileMode, error) {
	info, err := os.Stat(path)
	if errors.Is(err, os.ErrNotExist) {
		return "", 0o644, nil
	}
	if err != nil {
		return "", 0, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", 0, err
	}
	return string(data), info.Mode().Perm(), nil
}

// integrationHasKeys reports whether the installed file carries the key
// bindings, so that refreshing it keeps the choice the user made with --no-keys.
// The header records the choice; a file too old or too damaged to say is read
// for the dispatcher itself, and failing that treated as completion only, since
// adding a key binding nobody asked for is the worse of the two mistakes.
func integrationHasKeys(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	head := data
	if len(head) > 512 {
		head = head[:512]
	}
	if bytes.Contains(head, []byte("keys=yes")) {
		return true
	}
	if bytes.Contains(head, []byte("keys=no")) {
		return false
	}
	return bytes.Contains(data, []byte("_clihelp_explain"))
}
