package clihelp

import (
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// GenManPage writes a roff manual page for app: one page for the program, with
// a subsection for every command.
//
// This is a file for man(1), distinct from App.RenderMan, which renders the same
// material to a terminal with colors and hyperlinks in it. A generated page
// installed under $XDG_DATA_HOME/man is what makes zsh's run-help and fish's
// __fish_man_page — both bound to Alt-H by default — answer for a program that
// ships no manual of its own.
func GenManPage(app *App, w io.Writer) error {
	if app == nil {
		return errors.New("man page: app is nil")
	}
	var b strings.Builder
	writeManHeader(&b, app)
	writeManCommands(&b, app)
	writeManOptions(&b, "GLOBAL OPTIONS", manGlobalOptions(app))
	writeManExamples(&b, app)
	writeManNotes(&b, app)
	_, err := io.WriteString(w, b.String())
	return err
}

// manGlobalOptions gathers the options that apply to every command.
// manRagged sets ragged-right, unhyphenated text. A generated page carries URLs
// and flag specs that cannot be broken, and justifying around them makes troff
// warn and the output gappy. Every section heading resets adjustment, so this is
// re-asserted after each one.
func manRagged(b *strings.Builder) { b.WriteString(".ad l\n.nh\n") }

// manHeading writes a section or subsection heading, ragged right.
func manHeading(b *strings.Builder, macro, title string) {
	fmt.Fprintf(b, ".%s %s\n", macro, title)
	manRagged(b)
}

func manGlobalOptions(a *App) []Option {
	var opts []Option
	for _, o := range append(append([]Option{}, a.PersistentOptions...), a.GlobalFlags...) {
		if !o.Hidden {
			opts = append(opts, o)
		}
	}
	return opts
}

func writeManHeader(b *strings.Builder, app *App) {
	name := appName(app)
	version := app.Version
	if version != "" {
		version = name + " " + version
	} else {
		version = name
	}

	fmt.Fprintf(b, ".\\\" %s: %d\n", manMarker, manPageVersion)
	fmt.Fprintf(b, ".\\\" Generated by clihelp %s. Do not edit.\n", Version)
	fmt.Fprintf(b, ".TH %s 1 %s %s %s\n", thArg(strings.ToUpper(name)),
		thArg(time.Now().Format("2006-01-02")), thArg(version), thArg("User Commands"))
	manRagged(b)

	manHeading(b, "SH", "NAME")
	summary := manSummary(name, app.Description)
	if summary == "" {
		fmt.Fprintf(b, "%s\n", manEscape(name))
	} else {
		fmt.Fprintf(b, "%s \\- %s\n", manEscape(name), summary)
	}

	manHeading(b, "SH", "SYNOPSIS")
	fmt.Fprintf(b, ".B %s\n", manEscape(name))
	fmt.Fprintf(b, "[\\fIoptions\\fR] \\fIcommand\\fR [\\fIarguments\\fR]\n")

	if body := manText(appProse(app)); body != "" {
		manHeading(b, "SH", "DESCRIPTION")
		writeManParagraphs(b, body)
	}
}

// appProse is everything the application says about itself: its description,
// then the longer note when it carries one.
func appProse(a *App) string {
	parts := []string{}
	if a.Description != "" {
		parts = append(parts, a.Description)
	}
	if a.GlobalNote != "" && a.GlobalNote != a.Description {
		parts = append(parts, a.GlobalNote)
	}
	return strings.Join(parts, "\n\n")
}

func writeManCommands(b *strings.Builder, app *App) {
	var body strings.Builder
	_ = app.Walk(func(path []string, cmd *Command) error {
		if cmd.Hidden {
			return nil
		}
		manHeading(&body, "SS", manEscape(appName(app)+" "+strings.Join(path, " ")))
		if usage := manUsageLine(app, path, cmd); usage != "" {
			fmt.Fprintf(&body, ".B %s\n.br\n", usage)
		}
		if desc := manText(commandProse(cmd)); desc != "" {
			writeManParagraphs(&body, desc)
		}
		writeManParams(&body, cmd.Parameters)
		writeManOptionList(&body, append(append([]Option{}, cmd.PersistentOptions...), cmd.Options...))
		return nil
	})
	if body.Len() == 0 {
		return
	}
	manHeading(b, "SH", "COMMANDS")
	b.WriteString(body.String())
}

// manUsageLine is the command's usage, named from the program once. A UsageLine
// may or may not repeat the command's own path, so the program name is prepended
// only when it is not already there.
func manUsageLine(app *App, path []string, cmd *Command) string {
	usage := strings.TrimSpace(cmd.UsageLine)
	if usage == "" {
		return ""
	}
	name := appName(app)
	if !strings.HasPrefix(usage, name+" ") {
		usage = name + " " + usage
	}
	return manText(usage)
}

// manSummary is the one-line NAME description: inline markdown rendered away,
// no URL — a printed page has no room for one on that line — and the program's
// own name trimmed from the front, because the NAME line already names it.
func manSummary(name, description string) string {
	var b strings.Builder
	renderInline(&b, description)
	summary := FirstSentence(stripANSI(b.String()))
	if rest, found := strings.CutPrefix(summary, name); found {
		summary = strings.TrimLeft(rest, " \t\u2014\u2013-")
	}
	return manEscape(summary)
}

func commandProse(cmd *Command) string {
	if cmd.LongDescription != "" {
		return cmd.LongDescription
	}
	return cmd.Description
}

func writeManParams(b *strings.Builder, params []Param) {
	for _, p := range params {
		if p.Name == "" {
			continue
		}
		fmt.Fprintf(b, ".TP\n.I %s\n%s\n", manEscape(p.Name), orDash(manText(p.Description)))
	}
}

func writeManOptions(b *strings.Builder, heading string, opts []Option) {
	if len(opts) == 0 {
		return
	}
	manHeading(b, "SH", heading)
	writeManOptionList(b, opts)
}

func writeManOptionList(b *strings.Builder, opts []Option) {
	for _, opt := range opts {
		if opt.Hidden {
			continue
		}
		spec := parseFlagSpec(opt.Flags)
		if len(spec.longNames) == 0 && len(spec.shortNames) == 0 {
			continue
		}
		desc := manText(opt.Description)
		if opt.DefaultText != "" {
			desc = strings.TrimSpace(desc + " (default: " + manEscape(opt.DefaultText) + ")")
		}
		if opt.Deprecated != "" {
			desc = strings.TrimSpace(desc + " (deprecated: " + manText(opt.Deprecated) + ")")
		}
		fmt.Fprintf(b, ".TP\n.B %s\n%s\n", manEscape(opt.Flags), orDash(desc))
	}
}

func writeManExamples(b *strings.Builder, app *App) {
	var body strings.Builder
	writeExampleBlock(&body, app.Examples)
	_ = app.Walk(func(_ []string, cmd *Command) error {
		if !cmd.Hidden {
			writeExampleBlock(&body, cmd.Examples)
		}
		return nil
	})
	if body.Len() == 0 {
		return
	}
	manHeading(b, "SH", "EXAMPLES")
	b.WriteString(body.String())
}

func writeExampleBlock(b *strings.Builder, examples []Example) {
	for _, ex := range examples {
		for _, line := range splitLines(ex.Line) {
			if strings.TrimSpace(line) == "" {
				continue
			}
			fmt.Fprintf(b, ".TP\n.B %s\n", manEscape(line))
			fmt.Fprintf(b, "%s\n", orDash(manText(ex.Description)))
		}
	}
}

// writeManNotes emits the notes attached to commands, under the command they
// belong to being impractical in one flat page, so they are gathered here.
func writeManNotes(b *strings.Builder, app *App) {
	var body strings.Builder
	_ = app.Walk(func(path []string, cmd *Command) error {
		if cmd.Hidden {
			return nil
		}
		for _, note := range cmd.Notes {
			heading := strings.TrimSpace(note.Heading)
			if heading == "" {
				heading = "Notes"
			}
			manHeading(&body, "SS", manEscape(strings.Join(path, " "))+": "+manEscape(heading))
			writeManNoteBody(&body, note)
		}
		return nil
	})
	if body.Len() == 0 {
		return
	}
	manHeading(b, "SH", "NOTES")
	b.WriteString(body.String())
}

func writeManNoteBody(b *strings.Builder, note Note) {
	if note.Raw {
		b.WriteString(".nf\n")
		for _, line := range splitLines(note.Text) {
			fmt.Fprintf(b, "%s\n", manEscape(line))
		}
		b.WriteString(".fi\n")
		return
	}
	writeManParagraphs(b, manText(note.Text))
}

// writeManParagraphs emits text as roff paragraphs, so that a blank line in the
// source becomes a paragraph break rather than disappearing.
func writeManParagraphs(b *strings.Builder, text string) {
	first := true
	for _, para := range strings.Split(text, "\n\n") {
		para = strings.TrimSpace(para)
		if para == "" {
			continue
		}
		if !first {
			b.WriteString(".PP\n")
			manRagged(b)
		}
		first = false
		fmt.Fprintf(b, "%s\n", para)
	}
}

func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "\\-"
	}
	return s
}

// manText renders inline markdown to the plain text a manual page wants — a
// link becomes "text (url)", because a printed page cannot be clicked — and then
// escapes it for roff.
func manText(s string) string {
	var b strings.Builder
	renderInline(&b, s, true)
	return manEscape(stripANSI(b.String()))
}

// thArg quotes one argument of the .TH line.
//
// Go's %q was being used here, which escapes for Go: it emits \" — roff's
// comment-to-end-of-line — so a version string carrying a quote truncated the
// header and silently dropped every argument after it, including the section
// title. roff's own convention is a double-quoted argument with embedded quotes
// doubled, and manEscape first neutralises the backslash escapes.
func thArg(s string) string {
	s = strings.NewReplacer("\n", " ", "\r", " ").Replace(s)
	return `"` + strings.ReplaceAll(manEscape(s), `"`, `""`) + `"`
}

// manEscape makes a string safe as roff input: a backslash would start an escape
// sequence, and a line beginning with "." or "'" would be read as a request.
func manEscape(s string) string {
	s = strings.NewReplacer(
		"\\", "\\e",
		"\u2014", "\\(em",
		"\u2013", "\\(en",
		"\u2026", "\\&...",
	).Replace(s)
	lines := splitLines(s)
	for i, line := range lines {
		if strings.HasPrefix(line, ".") || strings.HasPrefix(line, "'") {
			lines[i] = "\\&" + line
		}
	}
	return strings.Join(lines, "\n")
}

// manMarker labels a generated page, so an upgrade can tell one clihelp wrote
// from one a distribution packaged.
const manMarker = "clihelp-manpage-version"

// ManPagePath returns where a generated manual page is installed for this user.
// $XDG_DATA_HOME/man is on man's default search path, so nothing has to be
// configured for it to be found.
func ManPagePath(app *App) (string, error) {
	if app == nil {
		return "", errors.New("man page path: app is nil")
	}
	name, err := safeAppName(app)
	if err != nil {
		return "", err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to locate user home directory: %w", err)
	}
	dataHome := os.Getenv("XDG_DATA_HOME")
	if dataHome == "" {
		dataHome = filepath.Join(home, ".local", "share")
	}
	return filepath.Join(dataHome, "man", "man1", name+".1"), nil
}

// InstallManPage writes the generated page under the user's data directory and
// returns its path.
//
// It refuses when a manual page for this program already exists somewhere else,
// because which of two pages man(1) shows is not something a program can
// predict, and the one that loses is invisible. force installs anyway.
func InstallManPage(app *App, force bool) (string, error) {
	target, err := ManPagePath(app)
	if err != nil {
		return "", err
	}
	if !force {
		if other, found := manPageElsewhere(app, target); found {
			return "", fmt.Errorf("a manual page for %s is already installed at %s; pass --force to install this one as well", appName(app), other)
		}
	}

	var page strings.Builder
	if err := GenManPage(app, &page); err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return "", fmt.Errorf("failed to create directory %q: %w", filepath.Dir(target), err)
	}
	if err := writeFileAtomically(target, []byte(page.String()), 0o644); err != nil {
		return "", fmt.Errorf("failed to write %q: %w", target, err)
	}
	return target, nil
}

// UninstallManPage removes a page clihelp generated, and leaves any other alone.
func UninstallManPage(app *App) (string, error) {
	target, err := ManPagePath(app)
	if err != nil {
		return "", err
	}
	if !isGeneratedManPage(target) {
		return "", nil
	}
	if err := os.Remove(target); err != nil {
		return "", err
	}
	return target, nil
}

// manPageElsewhere asks man(1) where it would find a page for this program, and
// reports one that is not ours. When man is not installed there is nothing to
// collide with as far as this machine is concerned.
func manPageElsewhere(app *App, target string) (string, bool) {
	out, err := exec.Command("man", "-w", appName(app)).Output()
	if err != nil {
		return "", false
	}
	for _, line := range splitLines(strings.TrimSpace(string(out))) {
		line = strings.TrimSpace(line)
		if line == "" || line == target {
			continue
		}
		return line, true
	}
	return "", false
}

// isGeneratedManPage reports whether the file at path carries clihelp's marker.
func isGeneratedManPage(path string) bool {
	return fileHasMarker(path, manMarker, markerWindow)
}

// manPageIsCurrent reports whether an installed page was generated by this
// version of the template.
func manPageIsCurrent(path string) bool {
	return fileHasMarker(path, fmt.Sprintf("%s: %d", manMarker, manPageVersion), markerWindow)
}

// refreshManPage keeps a manual page clihelp generated up to date when the
// template changes, and never creates one: installing a page is the user's
// decision, taken by running "__clihelp manpage --install".
func (a *App) refreshManPage() {
	path, err := ManPagePath(a)
	if err != nil || !isGeneratedManPage(path) || manPageIsCurrent(path) {
		return
	}
	_, _ = InstallManPage(a, true)
}

// manPageAction is the behaviour behind both "__clihelp manpage" and the
// optional visible command: print the page, or install or remove it.
func (a *App) manPageAction(out, notes io.Writer, install, uninstall, force bool) error {
	// The usage says "[--install|--uninstall]"; make the bar mean something
	// rather than silently preferring one. --force applies to installing, so on
	// its own it was accepted and ignored.
	if install && uninstall {
		return errors.New("--install and --uninstall are mutually exclusive")
	}
	if force && !install {
		return errors.New("--force applies to --install")
	}
	switch {
	case uninstall:
		path, err := UninstallManPage(a)
		if err != nil {
			return err
		}
		if path == "" {
			fmt.Fprintln(notes, "no generated manual page to remove")
			return nil
		}
		// The path alone on stdout, so it can be captured; the sentence on stderr.
		fmt.Fprintln(out, path)
		fmt.Fprintf(notes, "removed %s\n", path)
		return nil
	case install:
		path, err := InstallManPage(a, force)
		if err != nil {
			return err
		}
		fmt.Fprintln(out, path)
		fmt.Fprintf(notes, "installed the manual page; 'man %s' will find it, and so will Alt-H in zsh and fish\n", appName(a))
		return nil
	}
	return GenManPage(a, out)
}

// ManPageCommand returns a command that prints the program's manual page, or
// installs it for man(1). Add it to App.Commands to offer it; the same thing is
// always reachable through "__clihelp manpage", author opt-in or not.
//
// A generated page makes zsh's run-help and fish's man-page key — both bound to
// Alt-H by default — answer for a program that ships no manual of its own.
func ManPageCommand() Command {
	var install, uninstall, force bool
	return Command{
		Name:        "manpage",
		Description: "Print the manual page, or install it for man(1)",
		UsageLine:   "manpage [--install|--uninstall] [--force]",
		Examples: []Example{
			{Line: "manpage > myapp.1", Description: "Write the page for a package to install"},
			{Line: "manpage --install", Description: "Install it for this user"},
		},
		Options: []Option{
			Bool(&install, "--install", false, "Install it under the user's data directory, where man(1) looks"),
			Bool(&uninstall, "--uninstall", false, "Remove a manual page installed this way"),
			Bool(&force, "--force", false, "Install even though another manual page for this program exists"),
		},
		Notes: []Note{
			{
				Heading: "Installing",
				Text:    "Installation refuses when a manual page for this program already exists elsewhere, because which of two pages man(1) shows is not predictable and the one that loses is invisible. --force installs anyway.",
			},
		},
		Args: NoArgs,
		Run: func(ctx *Context) error {
			return ctx.App.manPageAction(ctx.Stdout, ctx.Stderr, install, uninstall, force)
		},
	}
}
