package clihelp

import (
	"errors"
	"fmt"
	"io"
	"strings"
)

// Argument names beginning with "__" are reserved by clihelp; an application
// must not declare commands with these names.
//
//	__complete   the completion protocol, called by the generated shell scripts
//	__explain    the Alt-H protocol, called by the generated key bindings
//	__clihelp    the setup verbs below
//
// The first two are a frozen boundary: installed scripts call them by name.
// Everything a human or a setup script invokes goes under __clihelp instead, so
// the reserved surface stays one word however many verbs are added.
//
// __clihelp answers in every clihelp program, whether or not its author added
// CompletionCommand() to the command tree. The capability was always universal —
// ExecuteContext serves __complete before it ever looks at the command tree —
// while the means of setting it up used to depend on the author opting in. That
// left a program that completes perfectly with no way to be asked to install its
// own completion, which is precisely the case a dotfiles script or a packager
// runs into.
//
// It is hidden, not secret: it is absent from help and completion output because
// no human needs it in the way, and it never acts unless it is invoked.
const (
	protoComplete = "__complete"
	protoExplain  = "__explain"
	protoClihelp  = "__clihelp"
)

// handleClihelpCommand serves "<app> __clihelp <verb> [args...]".
func (a *App) handleClihelpCommand(args []string) error {
	verb, rest := "", []string(nil)
	if len(args) > 0 {
		verb, rest = args[0], args[1:]
	}

	switch verb {
	case "":
		a.printClihelpVerbs(a.stdout())
		return nil
	case "version":
		fmt.Fprintf(a.stdout(), "clihelp %s\n", Version)
		return nil
	case "install":
		return a.clihelpInstall(rest)
	case "keys":
		return GenKeyBindings(a, firstArg(rest), a.stdout())
	case "wrapper":
		return a.clihelpWrapper(rest)
	default:
		return fmt.Errorf("unknown %s verb %q (try %s with no arguments)", protoClihelp, verb, protoClihelp)
	}
}

func firstArg(args []string) string {
	if len(args) > 0 {
		return args[0]
	}
	return ""
}

func (a *App) printClihelpVerbs(w io.Writer) {
	name := appName(a)
	fmt.Fprintf(w, "%s %s — shell integration for this program, built with clihelp %s\n\n", name, protoClihelp, Version)
	for _, line := range []string{
		"version                     report the clihelp version this program was built with",
		"install [<shell>]           install the completion script, printing its path",
		"keys [<shell>]              print the key bindings to source from a shell startup file",
		"wrapper <name> [<args>...]  print a wrapper script for this program, with arguments",
	} {
		fmt.Fprintf(w, "  %s %s\n", protoClihelp, line)
	}
	fmt.Fprintf(w, "\nSupported shells: %s\n", strings.Join(SupportedShells, ", "))
}

// clihelpInstall writes the installed path to stdout, alone, so that a script
// can capture it; anything for a human goes to stderr.
func (a *App) clihelpInstall(args []string) error {
	shell := firstArg(args)
	path, err := InstallCompletion(a, shell)
	if err != nil {
		return err
	}
	fmt.Fprintln(a.stdout(), path)
	if shell == "" {
		shell = detectShell()
	}
	fmt.Fprintf(a.stderr(), "installed the %s completion script; restart the shell to activate it\n", shell)
	return nil
}

// clihelpWrapper writes the wrapper script to stdout, alone, so that it can be
// redirected straight into a file; the line that registers it with the shell
// goes to stderr.
func (a *App) clihelpWrapper(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: %s wrapper <name> [<args>...]", protoClihelp)
	}
	name, wrapped := args[0], args[1:]
	if err := GenWrapperScript(a, name, wrapped, a.stdout()); err != nil {
		return err
	}
	printWrapperRegistration(a.stderr(), a, name, wrapped)
	return nil
}

const wrapperTemplate = `#!/bin/sh
# clihelp-wraps: {{target}}
#
# Wrapper for {{app}}, generated by "{{app}} {{proto}} wrapper {{name}}".
# Shell completion and the Alt-H explanation work through it because it answers
# clihelp's protocol calls on behalf of the program it wraps.

case $1 in
    __complete)
        shift
        exec {{app}} __complete {{args}} "$@"
        ;;
    __explain)
        # The first line of the answer is the command line to put back on the
        # prompt, and it is echoed back unchanged: rewriting "{{name}} ..." to
        # "{{target}} ..." would replace what was deliberately typed short.
        printf '%s\n' "$2"
        rest=${2#* }
        [ "$rest" = "$2" ] && rest=
        {{app}} __explain "{{target}} $rest" | tail -n +2
        exit 0
        ;;
esac

exec {{app}} {{args}} "$@"
`

// GenWrapperScript writes a wrapper script that invokes the application with
// args prepended, and forwards clihelp's protocol calls so that completion and
// Alt-H keep working through it.
//
// A wrapper is usually written by someone who is not the application's author,
// after it was built, which is why it carries its own "clihelp-wraps:" marker
// rather than the application declaring a list of wrappers it cannot know.
func GenWrapperScript(app *App, name string, args []string, w io.Writer) error {
	if app == nil {
		return errors.New("wrapper: app is nil")
	}
	if strings.TrimSpace(name) == "" {
		return errors.New("wrapper: a name is required")
	}

	quoted := make([]string, 0, len(args))
	for _, arg := range args {
		quoted = append(quoted, escapeShellArg(arg))
	}
	joined := strings.Join(quoted, " ")

	target := appName(app)
	if joined != "" {
		target += " " + joined
	}

	script := strings.NewReplacer(
		"{{app}}", appName(app),
		"{{name}}", name,
		"{{args}}", joined,
		"{{target}}", target,
		"{{proto}}", protoClihelp,
	).Replace(wrapperTemplate)
	_, err := io.WriteString(w, script)
	return err
}

// printWrapperRegistration prints the one line that tells a shell to complete
// name the way it completes the wrapped program. No shell will call a completion
// function for a name it was never told about, so this line is unavoidable —
// it is the same shape as git's __git_complete.
func printWrapperRegistration(w io.Writer, app *App, name string, args []string) {
	fn := strings.ReplaceAll(appName(app), "-", "_")
	target := appName(app)
	if len(args) > 0 {
		target += " " + strings.Join(args, " ")
	}

	lines := map[string]string{
		"bash": fmt.Sprintf("complete -F _%s_complete %s", fn, name),
		"zsh":  fmt.Sprintf("compdef _%s %s", fn, name),
		"fish": fmt.Sprintf("complete -c %s --wraps %s", name, escapeShellArg(target)),
	}

	fmt.Fprintf(w, "\n# Put %s somewhere on your PATH, then register it with your shell,\n", name)
	fmt.Fprintf(w, "# after the completion script for %s has been loaded:\n", appName(app))
	shell := detectShell()
	if line, ok := lines[shell]; ok {
		fmt.Fprintf(w, "#   %s\n", line)
		return
	}
	for _, s := range SupportedShells {
		fmt.Fprintf(w, "#   %-5s %s\n", s+":", lines[s])
	}
}
