package clihelp

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Wrappers are registered by the shell integration, not by the user.
//
// A wrapper generated by "__clihelp wrapper" says what it wraps in its second
// line. Registering it used to be two lines the user pasted into a startup file
// — after compinit, after the program's own completion, in that shell's syntax,
// and naming the Alt-H registry's wire format — which is the multi-step setup
// this library exists to remove. Instead, writing the integration file looks
// for marked wrappers on $PATH and registers each one in the file itself, so
// "install" once more is the whole of it, and "uninstall" takes them away.

// wrapperMarkerPrefix opens the second line of every generated wrapper.
const wrapperMarkerPrefix = "# clihelp-wraps: "

// wrapperHeadLimit bounds what is read of each file on $PATH; the marker is on
// the second line, so this only has to cover a shebang.
const wrapperHeadLimit = 512

// foundWrapper is a marked wrapper of this program found on $PATH.
type foundWrapper struct {
	name   string // the command name, its file's base name
	target string // the wrapped command line as the marker spells it, shell-quoted
}

// discoverWrappers finds the marked wrappers of app on $PATH. A name is taken
// from the first directory that has it, as the shell would run it; a name that
// cannot be a command name or a shell word is skipped, because the marker is
// read from a file anyone may have written and ends up in generated source.
func discoverWrappers(app string) []foundWrapper {
	var found []foundWrapper
	seen := map[string]bool{app: true}
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" {
			continue
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			name := entry.Name()
			if seen[name] || entry.IsDir() || safeWrapperName(name) != nil {
				continue
			}
			if target, ok := readWrapperMarker(filepath.Join(dir, name), app); ok {
				seen[name] = true
				found = append(found, foundWrapper{name: name, target: target})
			}
		}
	}
	return found
}

// readWrapperMarker returns the wrapped command line recorded in the file at
// path, when the file is an executable wrapper of app.
func readWrapperMarker(path, app string) (string, bool) {
	info, err := os.Stat(path)
	if err != nil || !info.Mode().IsRegular() || info.Mode().Perm()&0o111 == 0 {
		return "", false
	}
	f, err := os.Open(path)
	if err != nil {
		return "", false
	}
	defer f.Close()
	scanner := bufio.NewScanner(io.LimitReader(f, wrapperHeadLimit))
	for line := 0; line < 2 && scanner.Scan(); line++ {
		target, ok := strings.CutPrefix(scanner.Text(), wrapperMarkerPrefix)
		if !ok {
			continue
		}
		words, err := tokenizeShellWords(target)
		if err != nil || len(words) == 0 || words[0] != app {
			return "", false
		}
		return target, true
	}
	return "", false
}

// genWrapperRegistrations writes the lines that register each wrapper with
// shell's completion and, when keys is set, with the Alt-H registry. It comes
// after the program's own completion and key bindings in the integration file,
// so everything it names already exists.
func genWrapperRegistrations(app, shell string, keys bool, wrappers []foundWrapper, w io.Writer) {
	if len(wrappers) == 0 {
		return
	}
	fn := shellFuncName(app)
	names := make([]string, len(wrappers))
	for i, wr := range wrappers {
		names[i] = wr.name
	}
	fmt.Fprintf(w, "\n# Wrappers of %s found on $PATH when this file was written. Run\n", app)
	fmt.Fprintf(w, "# install again after adding or removing one.\n")
	switch shell {
	case "bash":
		fmt.Fprintf(w, "complete -o default -F _%s_complete %s\n", fn, strings.Join(names, " "))
	case "zsh":
		fmt.Fprintf(w, zshWrapperCompdef, fn, strings.Join(names, " "))
	case "fish":
		// --wraps hands fish's completer the expanded line, preset arguments
		// included, so the program's own completion answers it unchanged.
		for _, wr := range wrappers {
			fmt.Fprintf(w, "complete -c %s --wraps %s\n", wr.name, escapeFishArg(wr.target))
		}
	}
	if keys {
		genWrapperRegistry(shell, names, w)
	}
}

// zshWrapperCompdef registers the wrappers with compdef, now or — when compinit
// has not run yet — at the first prompt, as the program's own completion does.
const zshWrapperCompdef = `if type compdef >/dev/null 2>&1; then
    compdef _%[1]s %[2]s
else
    _%[1]s_wrappers_compdef() {
        type compdef >/dev/null 2>&1 || return
        compdef _%[1]s %[2]s
        add-zsh-hook -d precmd _%[1]s_wrappers_compdef
        unfunction _%[1]s_wrappers_compdef
    }
    autoload -Uz add-zsh-hook 2>/dev/null &&
        add-zsh-hook precmd _%[1]s_wrappers_compdef
fi
`

// genWrapperRegistry adds each wrapper to the Alt-H dispatcher's registry, in
// the "name:protocol" form the key-binding snippets read. Without it a
// wrapper's own __explain branch is unreachable from the key.
func genWrapperRegistry(shell string, names []string, w io.Writer) {
	for _, name := range names {
		entry := fmt.Sprintf("%s:%d", name, explainProtocolVersion)
		switch shell {
		case "bash":
			fmt.Fprintf(w, "case \" ${_clihelp_apps:-} \" in *\" %[1]s \"*) ;; *) _clihelp_apps=\"${_clihelp_apps:-} %[1]s \" ;; esac\n", entry)
		case "zsh":
			// -g, as in the key-binding snippet: a plugin manager may source
			// this file from inside a function.
			fmt.Fprintf(w, "[[ \" ${_clihelp_apps:-} \" == *\" %[1]s \"* ]] || typeset -g _clihelp_apps=\"${_clihelp_apps:-} %[1]s \"\n", entry)
		case "fish":
			fmt.Fprintf(w, "contains -- %[1]s $_clihelp_apps; or set -g _clihelp_apps $_clihelp_apps %[1]s\n", entry)
		}
	}
}
